name: TestDemo

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Installing Java
              run: sudo apt-get install openjdk-11-jdk -y
            
            - name: Compling Code
              run: echo "Compiling Code" 

            - name: Test Code
              run: echo "Test Code" 

            
